#!/bin/bash
# This deploy hook gets executed after dependencies are resolved and the
# build hook has been run but before the application has been started back
# up again.  This script gets executed directly, so it could be python, php,
# ruby, etc.
 
// .openshift/action_hooks/deploy
#!/bin/bash
# .openshift/action_hooks/deploy
unset GIT_DIR
cd $OPENSHIFT_REPO_DIR
curl -sS https://getcomposer.org/installer | php
php composer.phar install --prefer-source --no-interaction  // the arguments is used to work around github api rate limits
php composer.phar dump-autoload