#!/bin/bash
# This deploy hook gets executed after dependencies are resolved and the
# build hook has been run but before the application has been started back
# up again.  This script gets executed directly, so it could be python, php,
# ruby, etc.
 
#!/bin/bash
# .openshift/action_hooks/deploy

ln -sf $OPENSHIFT_DATA_DIR/uploads $OPENSHIFT_REPO_DIR/www/imagens
cd $OPENSHIFT_REPO_DIR
curl -sS https://getcomposer.org/installer | php
php composer.phar dump-autoload